services:
  adminer:
    image: adminer
    container_name: adminer-chatapp
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080
  database:
    image: postgres
    container_name: postgres-chatapp
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp
